### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Username4723** [Factorio-Just-For-Fun/Blueprints#1]
- [x] Inactivity Timers on All Trains
- [ ] Add Yellow Belts to the Const Train
- [x] Update mskitty prints
- [x] Add cfras's module builds, add recycling, and optimize their undergrounds
- [x] Add Beacon Green Chips
- [x] Update MadKatz Refinery
- [x] Add Same-Side Smelting
- [ ]
